config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :quotes,only:[:index,:new,:create,:edit,:update,:destroy] do
  collection do
    post:confirm
  end
end

root 'quotes#index'

end

  

app/models/quote.rb
class Quote < ActiveRecord::Base
    validates :content, presence: true,length:{maximum:140}
 belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :quotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

PERMISSIBLE_ATTRIBUTES = %i(name)

protected


def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
  devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
   before_action :authenticate_user!
   before_action :set_quotes, only: [:edit, :update, :destroy]

  def index
    @quotes=Quote.all
  end

  def new
if params[:back]
@quotes=Quote.new(quotes_params)
else
  @quotes=Quote.new
end
  end


  def create
    @quotes=Quote.new(quotes_params)
    @quotes.user_id = current_user.id
    if @quotes.save

    redirect_to quotes_path,notice:"Your favorite quote has posted！"

  else
    render 'new'
  end
  end

  def confirm
    @quotes=Quote.new(quotes_params)
    render :new if @quotes.invalid?
  end

  def edit
  end

  def update
    if @quotes.update(quotes_params)
    redirect_to quotes_path,notice:'Updated '
  else
    render'edit'
  end
end

  def destroy
    @quotes.destroy

    redirect_to quotes_path
  end


  private
    def quotes_params
      params.require(:quote).permit(:content)
    end
    def set_quotes
      @quotes=Quote.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
     def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_quotes_path
    elsif action_name == 'edit'
      quote_path
    end
  end
    
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Quotes",new_quote_path %></li>
      <% if user_signed_in? %>
            <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'login', new_user_session_path %></li>
            <li><%= link_to 'sign_up', new_user_registration_path %></li>
          <% end %>
    </ul>
  </header>


<%= yield %>

  <footer>
    <p>運営会社Quotes株式会社</p>
    <p>© 2015-2016 Copyright Quotes Corp.</p>
  </footer>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quotes,url: choose_new_or_edit) do |f| %>
  
  <% if @quotes.errors.any? %>
    <div id="error_explanation">

      <h2><%= @quotes.errors.count %> piace of errors have found</h2>

      <ul>
      <% @quotes.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control'  %>
  <br>
  <%= f.submit 'Quote', class: 'btn btn-primary btn-block'  %>
<% end %>

<%= link_to "Home", quotes_path %>

app/views/quotes/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>Quote with the following contents</h3>

<%= form_for(@quotes) do |f| %>
  <%= f.hidden_field :content %>
  <p>Content  :  <%= @quotes.content %></p>
  <%= f.submit "Quote" ,class: 'btn btn-primary btn-block'  %>
<% end %>

<%= form_for(@quotes, url: new_quote_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "back",name:"back", class: 'btn btn-default btn-block' %>
<% end %>
  </div>
</div>

app/views/quotes/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

  <p id="notice"><%= notice %></p>
  <h3>Edit quotes</h3>

  <%= render 'form' %>

  </div>
</div>

app/views/quotes/index.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p><%= notice %></p>
    <div id="bloom"><img src="<%=asset_path"baloon.jpg"%>"></div><br>
    <p>Quotes is made for people who want to share your favorite quotes<br>
    You can also post quotes that you made.share with people from all over the world!</p>
    <div id="wisdom"><h1> ー Wisdom Quotes ー</h1></div>
    <% @quotes.each do |quote| %>
    <p><%= quote.user.name %></p>
      <p><%= quote.content %></p>
      <div id="edit">
        <%= link_to "Edit", edit_quote_path(quote.id), class: 'btn btn-default btn-sm btn-success'%>
        <%= link_to "Delete", quote_path(quote.id), method: :delete,data:{confirm:'Are you sure you want to delete this an awesome quote?'}, class: 'btn btn-default btn-sm btn btn-danger' %>
      </div>
    <% end %>
    <div id="quote"><%= link_to"Quote",new_quote_path %></div>
  </div>
</div>

app/views/quotes/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

     <p id="notice"><%= notice %></p>
     <h1>Quotes</h1>
     <%= render 'form' %>
    </div>
  </div>
</div>

app/views/top/index.html.erb
  <div id="bloom"><img src="<%=asset_path"baloon.jpg"%>"></div>
<h1>〜well-known quotes 〜</h1>
<p1>Quotes is made for people who want to share your favorite quotes </p1><br>
<p1>You can also post quotes that you made.share with people from all over the world!</p1>